---
name: sonarqube-release
director_uuid: 7d8250a8-459a-40be-8c3a-e6ac95aa91ce

release:
  name: sonarqube-release
  version: 1.0
compilation:
  cloud_properties:
    instance_type: m3.large
  network: private_network
  reuse_compilation_vms: true
  workers: 3

update:
  canaries: 1
  canary_watch_time: 120000
  update_watch_time: 120000
  max_in_flight: 4

networks:
- name: private_network
  subnets:
  - cloud_properties:
      subnet: subnet-d5af89a3
      security_groups:
      - pcf-stack-OpsManStack-HLX51TTHO61P-PcfOpsManagerSecurityGroup-1RKIZCNBZQK3Q
      - pcf-stack-OpsManStack-HLX51TTHO61P-PcfVmsSecurityGroup-S7ESFV1N2AXI
    gateway: 10.0.0.1
    dns: 
      - 10.0.0.2
    range: 10.0.0.0/16
    reserved:
    - 10.0.0.2-10.0.0.30
    static:
    - 10.0.0.31 - 10.0.0.32
  type: manual

- name: public_network
  type: vip
  cloud_properties: {}

resource_pools:
- name: m3-medium
  network: private_network
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: 3146.11
  cloud_properties:
    instance_type: t2.medium

jobs:
- name: mariadb
  instances: 1
  template: mariadb
  persistent_disk: 8192
  resource_pool: m3-medium
  networks:
  - name: private_network
    static_ips: 10.0.0.32
  properties:
    admin_username: root
    admin_password: openpaas
    sonar_username: sonar
    sonar_password: sonar

- name: sonarqube
  template: sonarqube
  instances: 1
  resource_pool: m3-medium
  networks:
  - name: private_network
    default: [dns,gateway]
    static_ips: 10.0.0.31
  - name: public_network
    static_ips: 52.203.83.160
  properties:
    sonar_username: sonar
    sonar_password: sonar
    sonar_port: 9000
    mariadb_ip: 10.0.0.32
  depends_on:
  - mariadb
